# Sandbox overrides

fastapi:
  image:
    tag: "c6cb4d05"

streamlit:
  image:
    tag: "c6cb4d05"
  service:
    type: LoadBalancer
    port: 8501
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      external-dns.alpha.kubernetes.io/hostname: "kafka-portal-sandbox.aws.internal"
  env:
    API_URL: "http://kafka-portal-api:8000"
