apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: confluent
spec:
  shortDescription: Interact with Confluent Platform
  description: |
    The official kubectl plugin for Confluent Platform
  version: v0.304.2
  homepage: https://github.com/confluentinc/kubectl-plugin/
  platforms:
    - uri: https://github.com/conflunetinc/releases/download/kubectl-confluent-darwin-amd64.tar.gz
      sha256: 14511e1166ac635227e0d3f66c2955d966136966fca84aeeb9d7fbb3b1d1016d
      files:
        - from: "*"
          to: "."
      bin: "./kubectl-confluent"
      selector:
        matchLabels:
          os: darwin
          arch: amd64
    - uri: https://github.com/conflunetinc/releases/download/kubectl-confluent-linux-amd64.tar.gz
      sha256: 4512c5f702782f31797fe101cc68cda856084f056a769c9de8fbeb661323865b
      files:
        - from: "*"
          to: "."
      bin: "./kubectl-confluent"
      selector:
        matchLabels:
          os: linux
          arch: amd64
    - uri: https://github.com/conflunetinc/releases/download//kubectl-confluent-windows-amd64.tar.gz
      sha256: f423a007f35b6db8a8fae48c729e6387f949a734f9cc09df52e019c8d88c12e9
      files:
        - from: "*"
          to: "."
      bin: "./kubectl-confluent.exe"
      selector:
        matchLabels:
          os: windows
          arch: amd64
