"""
GitHub PR creation.
Creates a branch, writes topic + user YAMLs into gitops/sandbox/kafka/,
then opens a PR. The GitHub Actions workflow auto-merges it.
"""

import os
from github import Github, GithubException

GITHUB_TOKEN = os.environ["GITHUB_TOKEN"]
REPO_NAME    = os.environ.get("GITHUB_REPO", "karthikvuppu/ltim-streaming-kafka")
BASE_BRANCH  = "main"


def create_pr(topic_name: str, topic_yaml: str, user_yaml: str, requested_by: str) -> str:
    """
    Returns the HTML URL of the created PR.
    """
    g    = Github(GITHUB_TOKEN)
    repo = g.get_repo(REPO_NAME)

    branch_name = f"topic/{topic_name}"

    # Create branch from latest main
    main_sha = repo.get_branch(BASE_BRANCH).commit.sha
    try:
        repo.create_git_ref(f"refs/heads/{branch_name}", main_sha)
    except GithubException as exc:
        # Branch already exists — delete and recreate (idempotent retry)
        if exc.status == 422:
            repo.get_git_ref(f"heads/{branch_name}").delete()
            repo.create_git_ref(f"refs/heads/{branch_name}", main_sha)
        else:
            raise

    # Commit KafkaTopic YAML
    topic_path = f"gitops/sandbox/kafka/topics/{topic_name}.yaml"
    _upsert_file(repo, topic_path, topic_yaml, branch_name,
                 f"Add KafkaTopic {topic_name}")

    # Commit KafkaUser YAML (if generated)
    if user_yaml:
        team = topic_name.split(".")[0]
        user_path = f"gitops/sandbox/kafka/users/{team}-producer.yaml"
        _upsert_file(repo, user_path, user_yaml, branch_name,
                     f"Add KafkaUser {team}-producer for {topic_name}")

    # Open PR
    pr = repo.create_pull(
        title=f"[Kafka] New topic: {topic_name}",
        body=(
            f"### Kafka Topic Request\n\n"
            f"| Field | Value |\n"
            f"|---|---|\n"
            f"| Topic | `{topic_name}` |\n"
            f"| Requested by | {requested_by} |\n\n"
            f"Auto-generated by Kafka Self-Service Portal.  \n"
            f"This PR will be auto-merged after validation."
        ),
        head=branch_name,
        base=BASE_BRANCH,
    )

    return pr.html_url


def _upsert_file(repo, path: str, content: str, branch: str, message: str) -> None:
    """Create or update a file on the given branch."""
    try:
        existing = repo.get_contents(path, ref=branch)
        repo.update_file(path, message, content, existing.sha, branch=branch)
    except GithubException as exc:
        if exc.status == 404:
            repo.create_file(path, message, content, branch=branch)
        else:
            raise
