apiVersion: v1
kind: Namespace
metadata:
  name: externaldns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: externaldns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::858242954753:role/DNS_Mapping_OIDC_Sandbox_External
  labels:
    app.kubernetes.io/name: external-dns
