apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-service
  namespace: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::572663323550:role/secrets_manager_sb_ext
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: global-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-north-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-service
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: c3-access
  namespace: confluent
spec:
  refreshInterval: "1m"  # May be set to zero to fetch and create it once
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: c3-access
    creationPolicy: Owner
  data:
    - secretKey: basic.txt
      remoteRef:
        key: sandbox/external/c3-access
        property: basic.txt
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: confluent-license
  namespace: confluent
spec:
  refreshInterval: "1m" # May be set to zero to fetch and create it once
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: confluent-license
    creationPolicy: Owner
  data:
    - secretKey: license.txt
      remoteRef:
        key: sandbox/external/confluent-license
        property: license.txt
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: credential
  namespace: confluent
spec:
  refreshInterval: "1m"  # May be set to zero to fetch and create it once
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: credential
    creationPolicy: Owner
  data:
    - secretKey: plain-users.json
      remoteRef:
        key: sandbox/external/credential
        property: plain-users.json
    - secretKey: plain.txt
      remoteRef:
        key: sandbox/external/credential
        property: plain.txt
    - secretKey: digest-users.json
      remoteRef:
        key: sandbox/external/credential
        property: digest-users.json
    - secretKey: ldap.txt
      remoteRef:
        key: sandbox/external/credential
        property: ldap.txt
    - secretKey: digest.txt
      remoteRef:
        key: sandbox/external/credential
        property: digest.txt
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: digest-jaas
  namespace: confluent
spec:
  refreshInterval: "1m"  # May be set to zero to fetch and create it once
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: digest-jaas
    creationPolicy: Owner
  data:
    - secretKey: digest-jaas.conf
      remoteRef:
        key: sandbox/external/digest-jaas
        property: digest-jaas.conf
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mds-client-plain
  namespace: confluent
spec:
  refreshInterval: "1m"  # May be set to zero to fetch and create it once
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: mds-client-plain
    creationPolicy: Owner
  data:
    - secretKey: plain.txt
      remoteRef:
        key: sandbox/external/mds-client-plain
        property: plain.txt
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mds-client
  namespace: confluent
spec:
  refreshInterval: "1m"  # May be set to zero to fetch and create it once
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: mds-client
    creationPolicy: Owner
  data:
    - secretKey: bearer.txt
      remoteRef:
        key: sandbox/external/mds-client
        property: bearer.txt
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mds-token
  namespace: confluent
spec:
  refreshInterval: "1m"  # May be set to zero to fetch and create it once
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: mds-token
    creationPolicy: Owner
  data:
    - secretKey: mdsPublicKey.pem
      remoteRef:
        key: sandbox/external/mds-token
        property: mdsPublicKey.pem
    - secretKey: mdsTokenKeyPair.pem
      remoteRef:
        key: sandbox/external/mds-token
        property: mdsTokenKeyPair.pem
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rest-credential
  namespace: confluent
spec:
  refreshInterval: "1m"  # May be set to zero to fetch and create it once
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: rest-credential
    creationPolicy: Owner
  data:
    - secretKey: basic.txt
      remoteRef:
        key: sandbox/external/rest-credential
        property: basic.txt
#    - secretKey: bearer.txt
#      remoteRef:
#        key: sandbox/external/rest-credential
#        property: bearer.txt
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: restproxy-basic-client-jaas
  namespace: confluent
spec:
  refreshInterval: "1m"  # May be set to zero to fetch and create it once
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: restproxy-basic-client-jaas
    creationPolicy: Owner
  data:
    - secretKey: client.jaas
      remoteRef:
        key: sandbox/external/restproxy-basic-client-jaas
        property: client.jaas
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: restproxy-basic-users
  namespace: confluent
spec:
  refreshInterval: "1m"  # May be set to zero to fetch and create it once
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: restproxy-basic-users
    creationPolicy: Owner
  data:
    - secretKey: basic.txt
      remoteRef:
        key: sandbox/external/restproxy-basic-users
        property: basic.txt
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tls-group
  namespace: confluent
spec:
  refreshInterval: "1m"  # May be set to zero to fetch and create it once
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: tls-group
    creationPolicy: Owner
  data:
    - secretKey: fullchain.pem
      remoteRef:
        key: sandbox/external/tls-group
        property: fullchain.pem
    - secretKey: cacerts.pem
      remoteRef:
        key: sandbox/external/tls-group
        property: cacerts.pem
    - secretKey: privkey.pem
      remoteRef:
        key: sandbox/external/tls-group
        property: privkey.pem