apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: audit.transaction0.created
  namespace: kafka
  labels:
    strimzi.io/cluster: my-kafka
  annotations:
    requested-by: leelakrishna.yadav@ltimindtree.com
    description: create the topic
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 172800000
    cleanup.policy: delete
    min.insync.replicas: '1'
