apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: payments.e2etest.created
  namespace: kafka
  labels:
    strimzi.io/cluster: my-kafka
  annotations:
    requested-by: v.karthik@ltimindtree.com
    description: End to end test topic to verify OpenAI key is working correctly
spec:
  partitions: 2
  replicas: 1
  config:
    retention.ms: 86400000
    cleanup.policy: delete
    min.insync.replicas: '1'
